version: '3.8'

services:

  web:
    build: .
    command: bash -c "./app.sh"
    ports:
      - 8004:8000
    env_file:
      - .doc.env
    depends_on:
      - db
      - redis

  db:
    hostname: postgres
    image: postgres:15.3
    expose:
      - 5432
    env_file:
      - .doc.env

  redis:
    hostname: redis
    image: redis:latest
    expose:
      - 6379