"""05.12.2024 18:08

Revision ID: 00978cfac51f
Revises: fbc2c512c60b
Create Date: 2024-12-05 18:08:59.497466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00978cfac51f'
down_revision: Union[str, None] = 'fbc2c512c60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('basket_product_basket_id_fkey', 'basket_product', type_='foreignkey')
    op.drop_constraint('basket_product_product_id_fkey', 'basket_product', type_='foreignkey')
    op.create_foreign_key(None, 'basket_product', 'product', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'basket_product', 'basket', ['basket_id'], ['basket_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'basket_product', type_='foreignkey')
    op.drop_constraint(None, 'basket_product', type_='foreignkey')
    op.create_foreign_key('basket_product_product_id_fkey', 'basket_product', 'product', ['product_id'], ['product_id'])
    op.create_foreign_key('basket_product_basket_id_fkey', 'basket_product', 'basket', ['basket_id'], ['basket_id'])
    # ### end Alembic commands ###
