"""08.12.2024 10:08

Revision ID: 0d19e7fc99f0
Revises: a8a09b95f8e2
Create Date: 2024-12-08 10:08:46.180051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d19e7fc99f0'
down_revision: Union[str, None] = 'a8a09b95f8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket_product', sa.Column('buy_in_next_order', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basket_product', 'buy_in_next_order')
    # ### end Alembic commands ###
