"""06.12.2024 19:30

Revision ID: a8a09b95f8e2
Revises: 61a03d436d0f
Create Date: 2024-12-06 19:30:49.695409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a09b95f8e2'
down_revision: Union[str, None] = '61a03d436d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('order', sa.Column('order_price', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['user_id'])
    op.drop_column('order', 'amount')
    op.add_column('order_product', sa.Column('product_count', sa.Integer(), nullable=False))
    op.add_column('order_product', sa.Column('product_on_order_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product', 'product_on_order_price')
    op.drop_column('order_product', 'product_count')
    op.add_column('order', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'order_price')
    op.drop_column('order', 'user_id')
    # ### end Alembic commands ###
