"""02.12.2024 13:41

Revision ID: fbc2c512c60b
Revises: 41bf3cc5e6bd
Create Date: 2024-12-02 13:41:36.968387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc2c512c60b'
down_revision: Union[str, None] = '41bf3cc5e6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'basket_product', 'basket', ['basket_id'], ['basket_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'basket_product', type_='foreignkey')
    # ### end Alembic commands ###
